### ISSUE TITLE
Some suggestions and questions

### ISSUE THREAD

**Issue by 495FAB29** [lnbits/relampago#2]
Hi @fiatjaf, I found this repo when I was considering implementing something similar. An abstraction like this will be useful for a lot of people.

I would like to help with the development of relampago, but since it's brand new I would like to first get an idea of where you want to take it. I have a couple suggestions and questions would like to get your thoughts on:

1. Currently the abstraction clients must handle the logic for initializing the right type of backend. As more backends get added, it will be a lot of work for everyone to have to update their code to include the new option. A single Params type that includes configuration options for each backend could be used to allow relampago to handle this logic.
2. Go bindings are useful, but it would be more broadly useful to also provide an API of the abstraction. I have experience working with the same gRPC gateway LND uses, so I could implement a gRPC service and REST API that allows relampago to be optionally used as a standalone server.
3. Is your intention to keep relampago focused on lightning, or would you like to eventually also provide some on-chain functionality? This could also include things like a stream for new blocks.
4. Are you currently working on a LND backend? If not, I would like to implement it.

Looking forward to hearing your thoughts.

**Comment by fiatjaf** [comment]
Thank you for your interest.

1. How do you see this working? It would require manual work anyway from the consumers of this library to grab the params from their users or config files and fill in in the giobal `Params` struct, wouldn't it? I'm open to this possibility though.
2. I think that should be done in a different package that uses relampago, don't you think? I started this with the purpose of backing https://github.com/lnbits/lnbits-infinity, and that already provides an HTTP API, so there is that, but nothing prevents another gRPC API from being created.
3. Yes, I don't see how onchain stuff would fit relampago. Or maybe you're talking about the onchain APIs of each Lightning node implementation? If it's that than maybe we can include some other basic functions.
4. I am not. I have a bunch of backends planned and I'll need them to properly release https://github.com/lnbits/lnbits-infinity, but for now I'm working on other things. Would be great if you did the LND backend!

**Comment by 495FAB29** [comment]
1. That's right. Though with something like [go-flags](https://github.com/jessevdk/go-flags), it is quite easy to parse a config file that fits a struct. The library consumers would already have to fill the params anyway, this would just cut out the step of having a conditional to populate the correct backend-specific `Params` struct. 
2. That makes sense. Having that sort of thing in a separate package is probably better.
3. Understandable. I am referring to using the onchain APIs provided by the Lightning backends, but even going that route would probably be more trouble than it's worth. Just wanted to get your thoughts.
4. Sounds good. Expect a PR for that!
